# Variables Research (Part IV - Sales-related Variables)

### `Misael Ramirez - A00821781`

<img src="autlan-logo.png" alt="Autlan logo">


In this notebook, we will perform a research for a financial forecast of variables which driver is directly related with sales. Sales are divided in the following:
1. *Mining-Metallurgical Manganese Products*
2. *Energy*
3. *Precious Metals*

Nonetheless, the contribution of the **energy** division is technically none, since the resources related with energy are used in the mines possesed by Autlán to perform the extraction of minerals, manganese for the most part. As stated in 2Q14 report: 
> "The electricity generation of the Atexcaco hydroelectric plant was favored by the constant flow of water during the dry months, so its generation grew 56%, contributing 30% of Autlán's needs and representing savings in the first half of the year of 40.2 million MXN"

**Source:** Autlan

Now, we will focus on variables that use sales as a driver too, but this are more related with the way Autlán operates based on the forecasted sales.

In [1]:
# import required libraries 
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl

# setting up future plots
sns.set_style(  
    "darkgrid",  
    {  
        'legend.frameon': True,  
    }  
)
mpl.rc('figure', figsize=(14, 8))

## Cost of Gods Sold Forecast (2020-2025)

We perform a linear regression with the power of machine learning, dividing our data for trainign and the prediction itself. The COGS for FY20 will be calculated with the Sales from that same year we estimated through our research. 

The way we calculate gradients will be different, instead of modeling the next monetary quantity of COGS for the next years we will focus on the gradients directly for the forecast model. The percentage of COGS does not vary a lot over time (not even the gradient for FY20 which comes from forecasted numbers, COGS and Sales respectively), and this can be seen in its variance over time, which is `5.2415`, althugh we must keep in mind these are millions of dollars, it doesn't change as much.

We will use the following logic for the gradients

>**The years that the team considered of economic slowdown (FY20-FY22) will show a constat gradient of `plus 2 percent` in COGS until arriving to the years of economic recovery where COGS will show a constant gradient of `minus 2 percent`. It might not seem significant, but these are percentage movement for hunderds of millions of dollars**

These forecasted results in variables show a tendency very similar to the previous five years of analysis

In [2]:
print('Standard Deviation: {}'.format(np.std([72.39, 70.64, 65.90, 54.75, 66.64, 67.92, 66])))

Standard Deviation: 5.241501965767337


In [19]:
# import required libraries
from sklearn.linear_model import LinearRegression 

# create data for model
data = pd.read_excel('other_vars.xlsx', sheet_name='COGS_2', parse_dates=['Date'])

Y_train = data.loc[:,['COGS', 'Date']]
Y_train = Y_train.loc[Y_train['Date']<'2020'].drop('Date', axis=1)

X_train = data.loc[:,['Sales', 'Date']]
X_train = X_train.loc[X_train['Date']<'2020'].drop('Date', axis=1)

X_test = data.loc[:,['Sales', 'Date']]
X_test = X_test.loc[X_test['Date']>'2020'].drop('Date', axis=1)

# create model
reg = LinearRegression()
reg.fit(X_train,Y_train)
y_pred = reg.predict(X_test)
print('COGS FY20-25:\n{}'.format(y_pred))

COGS FY20-25:
[[209.309709  ]
 [231.40587663]
 [275.5982119 ]
 [278.27020091]
 [281.04825152]
 [283.93343254]]


In [4]:
show = pd.read_excel('other_vars.xlsx', sheet_name='COGS_2', parse_dates=['Date'])
show

Date       Sales     COGS         %
0  2014-12-31  338.040000  244.723  0.723900
1  2015-12-31  267.729000  189.118  0.706400
2  2016-12-31  230.711000  152.038  0.659000
3  2017-12-31  359.340000  196.723  0.547500
4  2018-12-31  413.504000  275.567  0.666400
5  2019-12-31  420.128000  285.362  0.679200
6  2020-12-31  315.090000  209.310  0.664286
7  2021-12-31  350.100000  231.410  0.660983
8  2022-12-31  420.120000  275.600  0.656003
9  2023-12-31  424.353600  278.270  0.655750
10 2024-12-31  428.755248  281.050  0.655502
11 2025-12-31  433.326637  283.930  0.655233

## General Expenses Forecast (2020-2025)

The General Expenses depend on the internal operations of Autlán, but it shows a imilar low variance gradients such as cost of good sold. As a result, GE for FY20 will be calculated with the Sales from that same year we estimated through our research.

The way we calculate gradients will be different, instead of modeling the next monetary quantity of GE for the next years we will focus on the gradients directly for the forecast model. The percentage of COGS does not vary a lot over time (not even the gradient for FY20 which comes from forecasted numbers, GE and Sales respectively), and this can be seen in its variance over time, which is `5.2415`, although we should keep in mind these are millions of dollars, it doesn't change as much.

We will use the following logic for the gradients

>**The years that the team considered of economic slowdown (FY20-FY22) will show a constat gradient of `plus 1 percent` in GE until arriving to the years of economic recovery where GE will show a constant gradient of `minus 1 percent`. It might not seem significant, but these are percentage movement for hunderds of millions of dollars.**

This results in variables show a tendency very similar to the previous five years of analysis

In [20]:
# import required libraries
from sklearn.linear_model import LinearRegression 

# create data for model
data = pd.read_excel('other_vars.xlsx', sheet_name='GE_2', parse_dates=['Date'])

Y_train = data.loc[:,['GE','Date']]
Y_train = Y_train.loc[Y_train['Date']<'2020'].drop('Date', axis=1)

X_train = data.loc[:,['Sales','Date']]
X_train = X_train.loc[X_train['Date']<'2020'].drop('Date', axis=1)

X_test = data.loc[:,['Sales','Date']]
X_test = X_test.loc[X_test['Date']>'2020'].drop('Date', axis=1)

# create model
reg = LinearRegression()
reg.fit(X_train,Y_train)
y_pred = reg.predict(X_test)
print('GE FY20-25:\n{}'.format(y_pred))

GE FY20-25:
[[38.91099025]
 [41.90134168]
 [47.88204456]
 [48.24365415]
 [48.61961743]
 [49.01007904]]


In [8]:
print('Standard Deviation: {}'.format(np.std([40.69, 36.31, 31.71, 39.65, 43.98, 52.98])))

Standard Deviation: 6.614914125586882


In [10]:
show = pd.read_excel('other_vars.xlsx', sheet_name='GE_2', parse_dates=['Date'])
show

Date       Sales      GE         %
0  2014-12-31  338.040000  40.693  0.120000
1  2015-12-31  267.729000  36.314  0.140000
2  2016-12-31  230.711000  31.707  0.140000
3  2017-12-31  359.340000  39.654  0.110000
4  2018-12-31  413.504000  43.980  0.110000
5  2019-12-31  420.128000  52.983  0.130000
6  2020-12-31  315.090000  38.910  0.123489
7  2021-12-31  350.100000  41.900  0.119680
8  2022-12-31  420.120000  47.880  0.113967
9  2023-12-31  424.353600  48.240  0.113679
10 2024-12-31  428.755248  48.610  0.113375
11 2025-12-31  433.326637  49.010  0.113102

## Capital Expenditure Forecast (2020-2025)

Due to the economic uncertainty, unnecesary risks will not be taken. Based on that, we consider a low CAPEX such as 2016 and 2017 for the years of economic turmoil defined by the team (2020-2022). It is important to highlight that this was before before acquiring Metallorum and having a 55% increase in CAPEXin 2018 as a result. CAPEX is not low-variance since this operations depend on acquisitions and investment decisions that are directly related with the operations that affected by the sales volume (e.g. Metallorum).

As a conclusion, we will apply the following logic for the gradients:

>**The forecast will be a low variance gradient as FY19 with a base gradient which increases 1% of the previous gradient each year as the economic turmoil finishes its period and the environment is open for more investment opportunities for autlán and to improve management operations of Metallorum as well. It might not seem significant, but these are percentage movement for hunderds of millions of dollars. We follow this model in order to keep a constant investment that displays the most normal fluctuations for the company**

In [21]:
# import required libraries
from sklearn.linear_model import LinearRegression 

# create data for model
data = pd.read_excel('other_vars.xlsx', sheet_name='CAPEX_2', parse_dates=['Date'])

Y_train = data.loc[:,['CAPEX%','Date']]
Y_train = Y_train.loc[Y_train['Date']<'2020'].drop('Date', axis=1)

X_train = data.loc[:,['Sales','Date']]
X_train = X_train.loc[X_train['Date']<'2020'].drop('Date', axis=1)

X_test = data.loc[:,['Sales','Date']]
X_test = X_test.loc[X_test['Date']>'2020'].drop('Date', axis=1)

# create model
reg = LinearRegression()
reg.fit(X_train,Y_train)
y_pred = reg.predict(X_test)
print('GE FY20-25:\n{}'.format(y_pred))

GE FY20-25:
[[0.17833145]
 [0.22984574]
 [0.33287432]
 [0.33910371]
 [0.34558037]
 [0.35230679]]


In [13]:
print('Standard Deviation: {}'.format(np.std([10.34, 2.91, 6.99, 55.59, 18.32])))

Standard Deviation: 19.064468521309482


In [14]:
data = pd.read_excel('other_vars.xlsx', sheet_name='CAPEX_2')
display(data)

Date       Sales    CAPEX%
0   2015-12-31  338.040000  0.103400
1   2016-12-31  267.729000  0.029100
2   2017-12-31  230.711000  0.069900
3   2018-12-31  359.340000  0.555900
4   2019-12-31  413.504000  0.183200
5   2020-12-31  315.090000  0.159000
6   2021-12-31  350.100000  0.160590
7   2022-12-31  420.120000  0.162196
8   2023-12-31  424.353600  0.163818
9   2024-12-31  428.755248  0.165456
10  2025-12-31  433.326637  0.167111

## Días Cuentas por Cobrar (Sales)

In [29]:
# import required libraries
from sklearn.linear_model import LinearRegression 

# create data for model
data = pd.read_excel('other_vars.xlsx', sheet_name='D2_2')

Y_train = data.loc[:,['D. CxC','Date']]
Y_train = Y_train.loc[Y_train['Date']<'2020'].drop('Date', axis=1)

X_train = data.loc[:,['Sales','Date']]
X_train = X_train.loc[X_train['Date']<'2020'].drop('Date', axis=1)

X_test = data.loc[:,['Sales','Date']]
X_test = X_test.loc[X_test['Date']>'2020'].drop('Date', axis=1)

# create model
reg = LinearRegression()
reg.fit(X_train,Y_train)
y_pred = reg.predict(X_test)
print('D. CxC FY20-25: \n{}'.format(y_pred))

D. CxC FY20-25: 
[[67.33904264]
 [66.47098919]
 [64.73488229]
 [64.62991254]
 [64.52077613]
 [64.40743107]]


In [24]:
print('Standard Deviation: {}'.format(np.std([56.26, 76.21, 75.54, 67.64, 58.17])))

Standard Deviation: 8.380970349547837


In [26]:
data = pd.read_excel('other_vars.xlsx', sheet_name='D2_2')
display(data)

Date       Sales  D. CxC
0   2015-12-31  267.729000   56.26
1   2016-12-31  230.711000   76.21
2   2017-12-31  359.340000   75.54
3   2018-12-31  413.504000   67.64
4   2019-12-31  420.128000   58.17
5   2020-12-31  315.090000   67.34
6   2021-12-31  350.100000   66.47
7   2022-12-31  420.120000   64.73
8   2023-12-31  424.353600   64.63
9   2024-12-31  428.755248   64.52
10  2025-12-31  433.326637   64.41

## Días Inventarios (COGS)

In [28]:
# import required libraries
from sklearn.linear_model import LinearRegression 

# create data for model
data = pd.read_excel('other_vars.xlsx', sheet_name='D3_2')

Y_train = data.loc[:,['D. Inventarios','Date']]
Y_train = Y_train.loc[Y_train['Date']<'2020'].drop('Date', axis=1)

X_train = data.loc[:,['COGS','Date']]
X_train = X_train.loc[X_train['Date']<'2020'].drop('Date', axis=1)

X_test = data.loc[:,['COGS','Date']]
X_test = X_test.loc[X_test['Date']>'2020'].drop('Date', axis=1)

# create model
reg = LinearRegression()
reg.fit(X_train,Y_train)
y_pred = reg.predict(X_test)
print('D. Inventarios FY20-25: \n{}'.format(y_pred))

D. Inventarios FY20-25: 
[[112.5564067 ]
 [116.41955017]
 [124.14408909]
 [124.61081276]
 [125.09676474]
 [125.60019702]]


In [30]:
print('Standard Deviation: {}'.format(np.std([108.05, 121.95, 103.35, 121.84, 146.55])))

Standard Deviation: 15.043337927468098


In [32]:
data = pd.read_excel('other_vars.xlsx', sheet_name='D3_2')
display(data)

Date     COGS  D. Inventarios
0   2015-12-31  216.686          108.05
1   2016-12-31  179.917          121.95
2   2017-12-31  221.194          103.35
3   2018-12-31  309.716          121.84
4   2019-12-31  341.905          146.55
5   2020-12-31  244.723          112.56
6   2021-12-31  189.118          116.42
7   2022-12-31  152.038          124.14
8   2023-12-31  196.723          124.61
9   2024-12-31  275.567          125.10
10  2025-12-31  285.362          125.60

## Días Proveedores (COGS)

In [36]:
# import required libraries
from sklearn.linear_model import LinearRegression 

# create data for model
data = pd.read_excel('other_vars.xlsx', sheet_name='D4_2')

Y_train = data.loc[:,['D. Proveedores','Date']]
Y_train = Y_train.loc[Y_train['Date']<'2020'].drop('Date', axis=1)

X_train = data.loc[:,['COGS','Date']]
X_train = X_train.loc[X_train['Date']<'2020'].drop('Date', axis=1)

X_test = data.loc[:,['COGS','Date']]
X_test = X_test.loc[X_test['Date']>'2020'].drop('Date', axis=1)

# create model
reg = LinearRegression()
reg.fit(X_train,Y_train)
y_pred = reg.predict(X_test)
print('D. Proveedores FY20-25: \n{}'.format(y_pred))

D. Proveedores FY20-25: 
[[102.44963171]
 [ 81.07972148]
 [ 66.8292715 ]
 [ 84.00244727]
 [114.30348498]
 [118.06786356]]


In [33]:
print('Standard Deviation: {}'.format(np.std([59.154, 96.296, 104.122, 119.385, 150.894])))

Standard Deviation: 29.95619213718593


In [34]:
data = pd.read_excel('other_vars.xlsx', sheet_name='D4_2')
display(data)

Date     COGS  D. Proveedores
0   2015-12-31  216.686          59.154
1   2016-12-31  179.917          96.296
2   2017-12-31  221.194         104.122
3   2018-12-31  309.716         119.385
4   2019-12-31  341.905         150.894
5   2020-12-31  244.723             NaN
6   2021-12-31  189.118             NaN
7   2022-12-31  152.038             NaN
8   2023-12-31  196.723             NaN
9   2024-12-31  275.567             NaN
10  2025-12-31  285.362             NaN